Repository scireum/sirius-db, pull requests merged in 2020-12, with the labels that each got.

#388 Adds a load metric counting secondary mongo metrics per minute and duration
  src/main/java/sirius/db/mongo/Finder.java
  src/main/java/sirius/db/mongo/Mango.java
  src/main/java/sirius/db/mongo/Mongo.java
  src/main/java/sirius/db/mongo/MongoMetricsProvider.java
  src/main/java/sirius/db/mongo/MongoQuery.java
Labels: 🧬 Enhancement

#389 Fix: Query Compilation when using References (SIRI-288)
  src/main/java/sirius/db/mixing/query/QueryCompiler.java
Labels: 🐛 Bugfix

#390 Fix: Typos
  src/main/java/sirius/db/es/RequestBuilder.java
  src/main/java/sirius/db/mixing/annotations/Versioned.java
Labels: 👶🏻 Trivial

#377 BREAKING: Valid languages for MultiLanguageString are now customizable
  src/main/java/sirius/db/mixing/properties/MultiLanguageStringProperty.java
  src/main/java/sirius/db/mixing/types/MultiLanguageString.java
  src/main/resources/component-db.conf
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringComposite.java
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringEntity.java
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringEntityWithMixin.java
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringMixin.java
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringPropertySpec.groovy
Labels:  💣 BREAKING CHANGE

#393 Makes a method public for reusage
  src/main/java/sirius/db/mixing/Property.java
Labels: 👶🏻 Trivial
