Repository scireum/sirius-db, pull requests merged in 2020-07, with the labels that each got.

#347 Adds elastic query helpers for adding an aggregation counting total hits
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#351 Simplifies and enhances creating and reading ES aggregations.
  src/main/java/sirius/db/es/AggregationBuilder.java
  src/main/java/sirius/db/es/AggregationResult.java
  src/main/java/sirius/db/es/Bucket.java
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 🧬 Enhancement

#354 Bug fixes for aggregation handling on ES queries
  src/main/java/sirius/db/es/AggregationResult.java
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#355 Restores support for aggregation results which are returned as map.
  src/main/java/sirius/db/es/AggregationResult.java
  src/main/java/sirius/db/es/Bucket.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#356 Adds support for transferring after keys as compound strings.
  src/main/java/sirius/db/es/AggregationBuilder.java
  src/main/java/sirius/db/es/AggregationResult.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#357 Fixes an NPE and adds a boilerplate getter.
  src/main/java/sirius/db/es/AggregationBuilder.java
  src/main/java/sirius/db/es/AggregationResult.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#363 Adds simple numerical Aggregations to Mango/MongoQuery
  src/main/java/sirius/db/mongo/MongoQuery.java
  src/test/java/sirius/db/mongo/MangoAggregationsTestEntity.java
  src/test/java/sirius/db/mongo/MangoSpec.groovy
Labels: 🧬 Enhancement

#362 BREAKING: Changes FieldLookupCache so it always returns the transformed value
  src/main/java/sirius/db/jdbc/OMA.java
  src/main/java/sirius/db/mixing/BaseMapper.java
  src/main/java/sirius/db/mixing/FieldLookupCache.java
  src/main/java/sirius/db/mixing/Property.java
  src/main/java/sirius/db/mixing/annotations/Mixin.java
  src/main/java/sirius/db/mixing/properties/BaseEntityRefProperty.java
  src/main/java/sirius/db/mixing/properties/BooleanProperty.java
  src/main/java/sirius/db/mixing/properties/EnumProperty.java
  src/main/java/sirius/db/mixing/properties/IntegerProperty.java
  src/main/java/sirius/db/mixing/properties/LongProperty.java
  src/main/java/sirius/db/mixing/properties/MultiPointLocationProperty.java
  src/main/java/sirius/db/mixing/properties/NestedListProperty.java
  src/main/java/sirius/db/mixing/properties/StringProperty.java
  src/main/java/sirius/db/mongo/Mango.java
  src/test/java/sirius/db/jdbc/FieldLookupCacheSpec.groovy
  src/test/java/sirius/db/mixing/fieldlookup/FieldLookupCacheSpec.groovy
  src/test/java/sirius/db/mixing/fieldlookup/MongoFieldLookUpTestEntity.java
  src/test/java/sirius/db/mixing/fieldlookup/MongoSuperHeroTestMixin.java
  src/test/java/sirius/db/mixing/fieldlookup/NameFieldsTestComposite.java
  src/test/java/sirius/db/mixing/fieldlookup/SQLFieldLookUpTestEntity.java
  src/test/java/sirius/db/mixing/fieldlookup/SQLSuperHeroTestMixin.java
Labels:  💣 BREAKING CHANGE

#365 Prevents a NPE when trying to access fallback on uninitialized multi lang data
  src/main/java/sirius/db/mixing/types/MultiLanguageString.java
Labels: 🐛 Bugfix, 👶🏻 Trivial
