Repository scireum/sirius-db, pull requests merged in 2020-02, with the labels that each got.

#273 Parses all kind of import values which aren't a list yet.
  src/main/java/sirius/db/mixing/properties/StringListProperty.java
Labels: 🐛 Bugfix

#276 Prevents an NPE if the requested entity doesn't exist.
  src/main/java/sirius/db/jdbc/OMA.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#277 Makes the schema sync more robust.
  src/main/java/sirius/db/jdbc/schema/Schema.java
Labels: 🎁 Next version, 🐛 Bugfix, 👶🏻 Trivial

#274 BREAKING: Specifies functional interface as indicated by sonarqube
  pom.xml
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/jdbc/BaseSQLQuery.java
  src/main/java/sirius/db/jdbc/SQLQuery.java
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/main/java/sirius/db/jdbc/TransformedQuery.java
  src/main/java/sirius/db/jdbc/batch/BatchSQLQuery.java
  src/main/java/sirius/db/jdbc/batch/external/ExternalBatchQuery.java
  src/main/java/sirius/db/mixing/AccessPath.java
  src/main/java/sirius/db/mixing/BaseEntity.java
  src/main/java/sirius/db/mixing/EntityDescriptor.java
  src/main/java/sirius/db/mixing/query/BaseQuery.java
  src/main/java/sirius/db/mongo/Finder.java
  src/main/java/sirius/db/mongo/MongoQuery.java
  src/test/java/sirius/db/jdbc/JDBCSpec.groovy
Labels:  💣 BREAKING CHANGE, 🎁 Next version, 👶🏻 Trivial

#278 BREAKING: Removes previously deprecated method 'getValue' in EntityRef
  src/main/java/sirius/db/mixing/types/BaseEntityRef.java
Labels:  💣 BREAKING CHANGE, 🎁 Next version, 👶🏻 Trivial

#280 SIRI-172 - add support for database supported optimistic locking patterns
  src/main/java/sirius/db/jdbc/OMA.java
  src/main/java/sirius/db/mixing/BaseMapper.java
  src/main/java/sirius/db/mixing/IntegrityConstraintFailedException.java
  src/main/java/sirius/db/mongo/Mango.java
  src/test/java/sirius/db/jdbc/JDBCSpec.groovy
  src/test/java/sirius/db/jdbc/OMASpec.groovy
  src/test/java/sirius/db/jdbc/SQLUniqueTestEntity.java
  src/test/java/sirius/db/jdbc/SmartQuerySpec.groovy
  src/test/java/sirius/db/jdbc/TransformedQuerySpec.groovy
  src/test/java/sirius/db/mongo/MangoSpec.groovy
  src/test/java/sirius/db/mongo/MongoUniqueTestEntity.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#279 Introduces support for MongoDB Multi-Language strings
  src/main/java/sirius/db/mixing/properties/MultiLanguageStringProperty.java
  src/main/java/sirius/db/mixing/types/MultiLanguageString.java
  src/main/resources/component-db.conf
  src/main/resources/db_de.properties
  src/main/resources/db_en.properties
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringEntity.java
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringPropertySpec.groovy
Labels: 🧬 Enhancement

#284 Improves error handling validations
  src/main/java/sirius/db/mixing/properties/MultiLanguageStringProperty.java
  src/main/java/sirius/db/mixing/types/MultiLanguageString.java
  src/main/resources/db_de.properties
  src/main/resources/db_en.properties
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringPropertySpec.groovy
Labels: 🧬 Enhancement

#285 Fixes the AmountProperty initialization check
  src/main/java/sirius/db/mixing/properties/AmountProperty.java
Labels: 🐛 Bugfix

#286 Adds support for Amount in mongoDB
  src/main/java/sirius/db/mixing/properties/AmountProperty.java
  src/test/java/sirius/db/mongo/properties/MongoAmountEntity.java
  src/test/java/sirius/db/mongo/properties/MongoAmountPropertySpec.groovy
Labels: 🐛 Bugfix

#290 fixes a random found mini typo and two for #school-english :)
  Readme.md
Labels: 👶🏻 Trivial

#292 Permits an entity to suppress an index defined by its parent.
  README.md
  src/main/java/sirius/db/jdbc/schema/Schema.java
  src/main/java/sirius/db/mixing/annotations/Index.java
  src/main/java/sirius/db/mongo/Mango.java
Labels: 🧬 Enhancement

#293 Makes forceEmpty in MongoOneInField work with list fields
  src/main/java/sirius/db/mongo/constraints/MongoOneInField.java
  src/test/java/sirius/db/mongo/MongoFilterFactorySpec.groovy
Labels: 🧬 Enhancement
