Repository scireum/sirius-db, pull requests merged in 2020-03, with the labels that each got.

#296 Aha/siri 187
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/main/java/sirius/db/mixing/query/BaseQuery.java
  src/main/java/sirius/db/mongo/Finder.java
  src/main/java/sirius/db/mongo/MongoQuery.java
  src/main/resources/component-db.conf
  src/test/java/sirius/db/jdbc/SmartQuerySpec.groovy
  src/test/java/sirius/db/mongo/MangoSpec.groovy
Labels: 🐛 Bugfix

#295 Adds 'wasCreated' method into BaseEntity to be called after save
  pom.xml
  src/main/java/sirius/db/es/ElasticEntity.java
  src/main/java/sirius/db/jdbc/SQLEntity.java
  src/main/java/sirius/db/mixing/BaseEntity.java
  src/main/java/sirius/db/mixing/annotations/AfterSave.java
  src/main/java/sirius/db/mixing/annotations/BeforeSave.java
  src/main/java/sirius/db/mongo/MongoEntity.java
  src/test/java/sirius/db/es/ElasticSpec.groovy
  src/test/java/sirius/db/es/ElasticWasCreatedTestEntity.java
  src/test/java/sirius/db/jdbc/OMASpec.groovy
  src/test/java/sirius/db/jdbc/SQLWasCreatedTestEntity.java
  src/test/java/sirius/db/mongo/MangoSpec.groovy
  src/test/java/sirius/db/mongo/MangoWasCreatedTestEntity.java
Labels: 🧬 Enhancement

#298 Adds helper methods to SafeList
  src/main/java/sirius/db/mixing/types/SafeList.java
Labels: 👶🏻 Trivial

#299 Permits to use a separate write index when updating ES entities.
  src/main/java/sirius/db/es/BulkContext.java
  src/main/java/sirius/db/es/ESIndexCommand.java
  src/main/java/sirius/db/es/Elastic.java
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/es/IndexMappings.java
  src/main/java/sirius/db/es/LowLevelClient.java
  src/main/java/sirius/db/es/RequestBuilder.java
  src/test/java/sirius/db/es/ElasticSpec.groovy
  src/test/java/sirius/db/es/ReindexSpec.groovy
Labels:  💣 BREAKING CHANGE
