Repository scireum/sirius-db, pull requests merged in 2021-06, with the labels that each got.

#424 fix skipping entities for iterateBlockwiseByPaging by limit with skip
  src/main/java/sirius/db/es/BulkResult.java
  src/main/java/sirius/db/es/Elastic.java
  src/main/java/sirius/db/es/constraints/NestedQuery.java
  src/main/java/sirius/db/jdbc/Database.java
  src/main/java/sirius/db/jdbc/Databases.java
  src/main/java/sirius/db/jdbc/GeneratedStatement.java
  src/main/java/sirius/db/jdbc/OMA.java
  src/main/java/sirius/db/jdbc/SQLQuery.java
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/main/java/sirius/db/jdbc/batch/BatchContext.java
  src/main/java/sirius/db/jdbc/batch/BatchQuery.java
  src/main/java/sirius/db/jdbc/batch/DeleteQuery.java
  src/main/java/sirius/db/jdbc/batch/FindQuery.java
  src/main/java/sirius/db/jdbc/batch/InsertQuery.java
  src/main/java/sirius/db/jdbc/batch/UpdateQuery.java
  src/main/java/sirius/db/jdbc/batch/external/ExternalBatchContext.java
  src/main/java/sirius/db/jdbc/batch/external/ExternalBatchQuery.java
  src/main/java/sirius/db/jdbc/constraints/Exists.java
  src/main/java/sirius/db/jdbc/constraints/Like.java
  src/main/java/sirius/db/jdbc/schema/DatabaseDialect.java
  src/main/java/sirius/db/jdbc/schema/Schema.java
  src/main/java/sirius/db/jdbc/schema/SchemaTool.java
  src/main/java/sirius/db/jdbc/schema/SchemaUpdateAction.java
  src/main/java/sirius/db/jdbc/schema/TableColumn.java
  src/main/java/sirius/db/mixing/BaseMapper.java
  src/main/java/sirius/db/mixing/properties/AmountProperty.java
  src/test/java/sirius/db/jdbc/OMASpec.groovy
  src/test/java/sirius/db/mongo/MangoSpec.groovy
Labels: 🐛 Bugfix

#427 Allows to use a script source as a query score
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/es/FunctionScoreBuilder.java
  src/main/java/sirius/db/es/ScriptScoreBuilder.java
  src/test/java/sirius/db/es/ElasticQuerySpec.groovy
Labels: 🧬 Enhancement

#428 activate nightly tests in drone
  .drone.yml
Labels: 👶🏻 Trivial

#429 Compares against the proper value when doing a change check.
  src/main/java/sirius/db/mixing/BaseEntity.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#431 Makes SQLQuery more robust.
  src/main/java/sirius/db/jdbc/SQLQuery.java
  src/main/java/sirius/db/jdbc/StatementCompiler.java
Labels: 🧬 Enhancement

#433 Bumps sirius-kernel
  pom.xml
Labels:  💣 BREAKING CHANGE, 👶🏻 Trivial
