Repository scireum/sirius-db, pull requests merged in 2021-03, with the labels that each got.

#413 Allows to filter on list field containing all provided values
  src/main/java/sirius/db/mixing/query/constraints/FilterFactory.java
  src/main/java/sirius/db/mongo/constraints/MongoFilterFactory.java
  src/test/java/sirius/db/es/ElasticQuerySpec.groovy
Labels: 👶🏻 Trivial, 🧬 Enhancement

#416 Extends SkipDefaultValue to empty maps and lists
  src/main/java/sirius/db/mongo/Mango.java
  src/test/java/sirius/db/mongo/MangoSpec.groovy
  src/test/java/sirius/db/mongo/SkipDefaultTestEntity.java
Labels: 👶🏻 Trivial

#417 Permits to subclass StringProperty and adds missing serial UIDs.
  src/main/java/sirius/db/es/types/ElasticRef.java
  src/main/java/sirius/db/jdbc/SQLEntityRef.java
  src/main/java/sirius/db/mixing/properties/StringProperty.java
  src/main/java/sirius/db/mongo/types/MongoRef.java
Labels: 👶🏻 Trivial

#418 Fixes microtiming for Mongo queries and adds additional timings for save and delete handlers.
  src/main/java/sirius/db/es/Elastic.java
  src/main/java/sirius/db/jdbc/OMA.java
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/main/java/sirius/db/mixing/BaseMapper.java
  src/main/java/sirius/db/mongo/Finder.java
  src/main/java/sirius/db/mongo/Mango.java
Labels: 🐛 Bugfix, 🧬 Enhancement
