Repository scireum/sirius-db, pull requests merged in 2021-09, with the labels that each got.

#445 Provides template classes for caching certain entity types.
  src/main/java/sirius/db/jdbc/SQLEntityCache.java
  src/main/java/sirius/db/mongo/MongoEntityCache.java
  src/main/java/sirius/db/util/BaseEntityCache.java
Labels: 🧬 Enhancement

#446 Permits to fetch the NLS key used to fetch the singular name of an entity
  pom.xml
  src/main/java/sirius/db/mixing/EntityDescriptor.java
Labels: 🧬 Enhancement

#447 Reverts to a previous logic
  src/main/java/sirius/db/mixing/EntityDescriptor.java
Labels: 👶🏻 Trivial, 🐛 Bugfix

#448 Builds an 'Entity cannot be saved' message
  src/main/java/sirius/db/mixing/BaseEntity.java
  src/main/java/sirius/db/mixing/EntityDescriptor.java
  src/main/resources/db_de.properties
  src/main/resources/db_en.properties
Labels: 🧬 Enhancement

#453 Clearifies the APIs provided by BaseQuery.
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/main/java/sirius/db/jdbc/TransformedQuery.java
  src/main/java/sirius/db/jdbc/constraints/CompoundValue.java
  src/main/java/sirius/db/jdbc/constraints/FieldOperator.java
  src/main/java/sirius/db/jdbc/constraints/RowValue.java
  src/main/java/sirius/db/jdbc/constraints/SQLFilterFactory.java
  src/main/java/sirius/db/mixing/query/BaseQuery.java
  src/main/java/sirius/db/mongo/Finder.java
  src/main/java/sirius/db/mongo/MongoQuery.java
  src/main/java/sirius/db/util/AutoClosingDoubleStream.java
  src/main/java/sirius/db/util/AutoClosingIntStream.java
  src/main/java/sirius/db/util/AutoClosingLongStream.java
  src/main/java/sirius/db/util/AutoClosingStream.java
  src/test/java/sirius/db/es/ElasticQuerySpec.groovy
  src/test/java/sirius/db/jdbc/SmartQuerySpec.groovy
  src/test/java/sirius/db/mongo/MangoSpec.groovy
Labels: 🐛 Bugfix,  💣 BREAKING CHANGE

#452 Fixes the "MongoEntity.isUnique" check for complex properties.
  src/main/java/sirius/db/mongo/MongoEntity.java
Labels: 🐛 Bugfix

#454 Drops milliseconds when persisting LocalDateTime in MongoDB
  src/main/java/sirius/db/mixing/EntityDescriptor.java
  src/main/java/sirius/db/mixing/properties/LocalDateTimeProperty.java
  src/main/java/sirius/db/mongo/constraints/MongoFilterFactory.java
Labels: 🐛 Bugfix

#456 Adds 'elemMatch' operation
  src/main/java/sirius/db/mongo/constraints/MongoFilterFactory.java
Labels: 🧬 Enhancement
