Repository scireum/sirius-db, pull requests merged in 2021-05, with the labels that each got.

#420 Permits to span an ELasticQuery across multiple indices.
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 🧬 Enhancement

#421 Enables one to configure the query iteration timeout in the corresponding configuration file
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/main/resources/component-db.conf
Labels: 👶🏻 Trivial

#422 Avoids idempotent Schema Change when @Length annotation is missing on a string field
  src/main/java/sirius/db/jdbc/schema/BasicDatabaseDialect.java
  src/main/java/sirius/db/mixing/Property.java
Labels: 🐛 Bugfix
