Repository scireum/sirius-db, pull requests merged in 2021-01, with the labels that each got.

#395 Switches some filter methods from List to more generic Collection
  src/main/java/sirius/db/mixing/query/constraints/FilterFactory.java
  src/main/java/sirius/db/mongo/constraints/MongoFilterFactory.java
  src/main/java/sirius/db/mongo/constraints/MongoOneInField.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#396 Allows @NullAllowed to work on MultiLanguageStrings
  src/main/java/sirius/db/mixing/properties/MultiLanguageStringProperty.java
  src/main/java/sirius/db/mixing/types/MultiLanguageString.java
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringComposite.java
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringEntity.java
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringMixin.java
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringPropertySpec.groovy
  src/test/java/sirius/db/mongo/properties/MongoMultiLanguageStringRequiredEntity.java
  src/test/resources/test_de.properties
Labels:  💣 BREAKING CHANGE

#397 Properly validates enum values provided from importers
  src/main/java/sirius/db/mixing/properties/EnumProperty.java
  src/test/java/sirius/db/mixing/properties/EnumPropertySpec.groovy
  src/test/resources/test_de.properties
Labels:  💣 BREAKING CHANGE, 🐛 Bugfix
