Repository scireum/sirius-db, pull requests merged in 2021-12, with the labels that each got.

#479 Provides a robust way of applying a query limit set by the user
  src/main/java/sirius/db/mixing/query/BaseQuery.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#480 Fallback to NLS.parseUserString when importing amounts
  src/main/java/sirius/db/mixing/properties/AmountProperty.java
Labels: 🧬 Enhancement

#481 Makes CONTAINS_ANY CSVFilter work correctly without orEmpty
  src/main/java/sirius/db/mixing/query/constraints/CSVFilter.java
Labels: 🐛 Bugfix
