Repository scireum/sirius-db, pull requests merged in 2021-10, with the labels that each got.

#460 Kills collation handling for MongoDB.
  src/main/java/sirius/db/es/constraints/BoolQueryBuilder.java
  src/main/java/sirius/db/mixing/properties/BooleanProperty.java
  src/main/java/sirius/db/mixing/properties/LongProperty.java
  src/main/java/sirius/db/mixing/properties/MultiPointLocationProperty.java
  src/main/java/sirius/db/mixing/properties/StringBooleanMapProperty.java
  src/main/java/sirius/db/mixing/query/constraints/FilterFactory.java
  src/main/java/sirius/db/mongo/Deleter.java
  src/main/java/sirius/db/mongo/Finder.java
  src/main/java/sirius/db/mongo/Mango.java
  src/main/java/sirius/db/mongo/Mongo.java
  src/main/java/sirius/db/mongo/SortField.java
  src/main/java/sirius/db/mongo/SortValue.java
  src/main/java/sirius/db/mongo/Updater.java
  src/main/resources/component-db.conf
  src/test/java/sirius/db/mongo/MongoFilterFactorySpec.groovy
Labels:  💣 BREAKING CHANGE

#461 Tries to prevent possible misuse of containsOne and containsNone
  src/main/java/sirius/db/mixing/query/constraints/FilterFactory.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#463 Moves SortField / SortValue to sirius-biz.
  src/main/java/sirius/db/mongo/CustomSortValues.java
  src/main/java/sirius/db/mongo/SortField.java
  src/main/java/sirius/db/mongo/SortValue.java
Labels: 🐛 Bugfix

#465 Mongo $size
  src/main/java/sirius/db/mongo/constraints/MongoFilterFactory.java
  src/test/java/sirius/db/mongo/MongoFilterFactorySpec.groovy
Labels: 👶🏻 Trivial

#466 Introduces onValidate in properties
  src/main/java/sirius/db/mixing/EntityDescriptor.java
  src/main/java/sirius/db/mixing/Property.java
Labels: 🧬 Enhancement
