Repository scireum/sirius-db, pull requests merged in 2022-09, with the labels that each got.

#519 SIRI-626 stream blockwise bug
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/test/java/sirius/db/jdbc/SmartQuerySpec.groovy
Labels: 🐛 Bugfix

#510 BREAKING: Replaces usage of _id by id
  src/main/java/sirius/db/es/Elastic.java
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/es/constraints/ElasticFilterFactory.java
Labels:  💣 BREAKING CHANGE

#522 Kills deprecated code and fixes sonarlint inspections.
  src/main/java/sirius/db/es/AggregationResult.java
  src/main/java/sirius/db/es/Bucket.java
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/es/IndexMappings.java
  src/main/java/sirius/db/es/LowLevelClient.java
  src/main/java/sirius/db/es/constraints/ElasticFilterFactory.java
  src/main/java/sirius/db/es/suggest/SuggestionResult.java
  src/main/java/sirius/db/es/suggest/TextPartSuggestion.java
  src/main/java/sirius/db/jdbc/BaseSQLQuery.java
  src/main/java/sirius/db/jdbc/Database.java
  src/main/java/sirius/db/jdbc/Databases.java
  src/main/java/sirius/db/jdbc/SQLEntityRef.java
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/main/java/sirius/db/jdbc/batch/BatchContext.java
  src/main/java/sirius/db/jdbc/batch/BatchQuery.java
  src/main/java/sirius/db/jdbc/batch/InsertQuery.java
  src/main/java/sirius/db/jdbc/batch/UpdateQuery.java
  src/main/java/sirius/db/jdbc/constraints/CombinedConstraint.java
  src/main/java/sirius/db/jdbc/constraints/Exists.java
  src/main/java/sirius/db/jdbc/schema/Schema.java
  src/main/java/sirius/db/mixing/DateRange.java
  src/main/java/sirius/db/mixing/properties/AmountProperty.java
  src/main/java/sirius/db/mixing/properties/IntegerProperty.java
  src/main/java/sirius/db/mixing/properties/LongProperty.java
  src/main/java/sirius/db/mixing/properties/MultiPointLocationProperty.java
  src/main/java/sirius/db/mixing/properties/NestedListProperty.java
  src/main/java/sirius/db/mixing/properties/StringBooleanMapProperty.java
  src/main/java/sirius/db/mixing/properties/StringIntMapProperty.java
  src/main/java/sirius/db/mixing/properties/StringListProperty.java
  src/main/java/sirius/db/mixing/properties/StringLocalDateTimeMapProperty.java
  src/main/java/sirius/db/mixing/properties/StringMapProperty.java
  src/main/java/sirius/db/mixing/properties/StringNestedMapProperty.java
  src/main/java/sirius/db/mixing/properties/StringProperty.java
  src/main/java/sirius/db/mixing/query/constraints/CSVFilter.java
  src/main/java/sirius/db/mixing/query/constraints/FilterFactory.java
  src/main/java/sirius/db/mixing/query/constraints/OneInField.java
  src/main/java/sirius/db/mixing/types/BaseEntityRef.java
  src/main/java/sirius/db/mixing/types/SafeList.java
  src/main/java/sirius/db/mongo/Updater.java
  src/main/java/sirius/db/mongo/constraints/MongoConstraint.java
  src/main/java/sirius/db/mongo/constraints/MongoFilterFactory.java
  src/main/java/sirius/db/mongo/facets/MongoDateRangeFacet.java
  src/main/java/sirius/db/redis/Redis.java
  src/main/java/sirius/db/text/PatternExtractProcessor.java
  src/main/java/sirius/db/text/PipelineProcessor.java
  src/test/java/sirius/db/es/ElasticQuerySpec.groovy
  src/test/java/sirius/db/es/LowLevelClientSpec.groovy
  src/test/java/sirius/db/es/ReindexSpec.groovy
Labels:  💣 BREAKING CHANGE

#524 Removes null byte char in Strings when loading SQL results into Row
  pom.xml
  src/main/java/sirius/db/jdbc/BaseSQLQuery.java
Labels: 👶🏻 Trivial, 🐛 Bugfix,  💣 BREAKING CHANGE
