Repository scireum/sirius-db, pull requests merged in 2022-05, with the labels that each got.

#500 Asserts modified fields
  src/main/java/sirius/db/mixing/BaseEntity.java
  src/main/resources/db_de.properties
  src/main/resources/db_en.properties
Labels: 🧬 Enhancement, 👶🏻 Trivial

#423 SkipDefaultValue: Improve handling/support and edge cases
  src/main/java/sirius/db/mixing/EntityDescriptor.java
  src/main/java/sirius/db/mongo/Mango.java
  src/test/java/sirius/db/mongo/MangoSpec.groovy
  src/test/java/sirius/db/mongo/SkipDefaultTestEntity.java
  src/test/kotlin/sirius/db/mixing/annotations/SkipDefaultValueTest.kt
Labels: 🧬 Enhancement, 🐛 Bugfix

#504 Transforms Amount to expected database values
  src/main/java/sirius/db/mixing/query/constraints/FilterFactory.java
Labels: 🧬 Enhancement
