Repository scireum/sirius-db, pull requests merged in 2022-10, with the labels that each got.

#526 Warns if an illegal combination of referential constraints are present.
  src/main/java/sirius/db/mixing/properties/BaseEntityRefProperty.java
  src/main/java/sirius/db/mixing/properties/SQLEntityRefProperty.java
Labels: 👶🏻 Trivial

#528 Permits to enable auto-commit in connections
  src/main/java/sirius/db/jdbc/Capability.java
  src/main/java/sirius/db/jdbc/Database.java
  src/main/java/sirius/db/jdbc/batch/BatchContext.java
  src/main/java/sirius/db/jdbc/batch/BatchQuery.java
  src/main/java/sirius/db/jdbc/batch/BatchSQLQuery.java
  src/main/java/sirius/db/jdbc/batch/DeleteQuery.java
  src/main/java/sirius/db/jdbc/batch/FindQuery.java
  src/main/java/sirius/db/jdbc/batch/InsertQuery.java
  src/main/java/sirius/db/jdbc/batch/UpdateQuery.java
Labels: 🧬 Enhancement

#530 Downgrades fastjson to 1.x version without CVE
  pom.xml
  src/main/java/sirius/db/es/Elastic.java
  src/main/java/sirius/db/es/ElasticEntity.java
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/es/suggest/SuggestPart.java
  src/main/java/sirius/db/es/suggest/SuggestionResult.java
  src/main/java/sirius/db/es/suggest/TextPartSuggestion.java
Labels: 👶🏻 Trivial, dependencies

#534 Refactors the bulk API to use the same refresh setting for all commits.
  src/main/java/sirius/db/es/BulkContext.java
  src/main/java/sirius/db/es/Elastic.java
Labels: 👶🏻 Trivial
