Repository scireum/sirius-db, pull requests merged in 2023-05, with the labels that each got.

#562 Fixes some search issues (SIRI-801 & SIRI-800)
  src/main/java/sirius/db/mixing/query/QueryCompiler.java
  src/test/java/sirius/db/jdbc/SQLQueryCompilerSpec.groovy
  src/test/java/sirius/db/jdbc/TestEntity.java
Labels: 🐛 Bugfix

#563 SIRI-738: Replace Elastic scrolling with PIT + Search After
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/es/LowLevelClient.java
  src/main/java/sirius/db/es/suggest/SuggestBuilder.java
  src/main/java/sirius/db/es/suggest/SuggestOption.java
  src/main/java/sirius/db/es/suggest/SuggestPart.java
  src/test/java/sirius/db/es/ElasticQuerySpec.groovy
  src/test/java/sirius/db/es/SuggestSpec.groovy
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#565 SmartQuery minor code cleanups
  src/main/java/sirius/db/jdbc/SmartQuery.java
Labels: 🧬 Enhancement

#567 Switches usage of FastJSON to Jackson for Handling JSONs
  pom.xml
  src/main/java/sirius/db/es/AggregationBuilder.java
  src/main/java/sirius/db/es/AggregationResult.java
  src/main/java/sirius/db/es/Bucket.java
  src/main/java/sirius/db/es/BulkContext.java
  src/main/java/sirius/db/es/BulkResult.java
  src/main/java/sirius/db/es/ESPropertyInfo.java
  src/main/java/sirius/db/es/Elastic.java
  src/main/java/sirius/db/es/ElasticEntity.java
  src/main/java/sirius/db/es/ElasticMetricsProvider.java
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/es/FunctionScoreBuilder.java
  src/main/java/sirius/db/es/IndexMappings.java
  src/main/java/sirius/db/es/LowLevelClient.java
  src/main/java/sirius/db/es/NearestNeighborsSearch.java
  src/main/java/sirius/db/es/RequestBuilder.java
  src/main/java/sirius/db/es/SettingsCustomizer.java
  src/main/java/sirius/db/es/SortBuilder.java
  src/main/java/sirius/db/es/constraints/BoolQueryBuilder.java
  src/main/java/sirius/db/es/constraints/ElasticCSVFilter.java
  src/main/java/sirius/db/es/constraints/ElasticConstraint.java
  src/main/java/sirius/db/es/constraints/ElasticFilterFactory.java
  src/main/java/sirius/db/es/constraints/NestedQuery.java
  src/main/java/sirius/db/es/suggest/SuggesterBuilder.java
  src/main/java/sirius/db/es/suggest/SuggestionQuery.java
  src/main/java/sirius/db/es/suggest/SuggestionResult.java
  src/main/java/sirius/db/es/suggest/TermSuggestion.java
  src/main/java/sirius/db/es/suggest/TextPartSuggestion.java
  src/main/java/sirius/db/es/types/DenseVectorProperty.java
  src/main/java/sirius/db/mixing/properties/AmountProperty.java
  src/main/java/sirius/db/mixing/properties/BaseEntityRefListProperty.java
  src/main/java/sirius/db/mixing/properties/BooleanProperty.java
  src/main/java/sirius/db/mixing/properties/ElasticRefProperty.java
  src/main/java/sirius/db/mixing/properties/EnumProperty.java
  src/main/java/sirius/db/mixing/properties/IntegerProperty.java
  src/main/java/sirius/db/mixing/properties/LocalDateProperty.java
  src/main/java/sirius/db/mixing/properties/LocalDateTimeProperty.java
  src/main/java/sirius/db/mixing/properties/LongProperty.java
  src/main/java/sirius/db/mixing/properties/MongoRefProperty.java
  src/main/java/sirius/db/mixing/properties/NestedListProperty.java
  src/main/java/sirius/db/mixing/properties/SQLEntityRefProperty.java
  src/main/java/sirius/db/mixing/properties/StringBooleanMapProperty.java
  src/main/java/sirius/db/mixing/properties/StringIntMapProperty.java
  src/main/java/sirius/db/mixing/properties/StringListProperty.java
  src/main/java/sirius/db/mixing/properties/StringLocalDateTimeMapProperty.java
  src/main/java/sirius/db/mixing/properties/StringMapProperty.java
  src/main/java/sirius/db/mixing/properties/StringProperty.java
  src/main/java/sirius/db/qdrant/Match.java
  src/main/java/sirius/db/qdrant/Point.java
  src/main/java/sirius/db/qdrant/QdrantDatabase.java
  src/main/java/sirius/db/qdrant/Search.java
  src/main/java/sirius/db/util/Tensors.java
  src/test/java/sirius/db/es/ElasticQuerySpec.groovy
  src/test/java/sirius/db/es/LowLevelClientSpec.groovy
  src/test/java/sirius/db/es/SuggestSpec.groovy
Labels:  💣 BREAKING CHANGE

#568 Cleanup: Dependency on FastJSON
  pom.xml
Labels: 👶🏻 Trivial

#570 Warns about wrong nullable annotation on entity properties
  src/main/java/sirius/db/mixing/Property.java
Labels: 🧬 Enhancement, 👶🏻 Trivial
