Repository scireum/sirius-db, pull requests merged in 2023-07, with the labels that each got.

#579 Prevents loosing named queries if only a single condition is present
  src/main/java/sirius/db/es/constraints/BoolQueryBuilder.java
Labels: 👶🏻 Trivial, 🐛 Bugfix

#581 Adds 2nd level collapsing and permits to changes the ES indices being queried
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#583 Permits to delay specifying the actual indices to query in an ElasticQuery
  src/main/java/sirius/db/es/Elastic.java
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/mixing/query/BaseQuery.java
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE, 🔥 Hotfix

#584 Permits applying the same order of a query "down" to its inner hits
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 🧬 Enhancement

#582 Allows to define shared validators for properties
  src/main/java/sirius/db/mixing/Property.java
  src/main/java/sirius/db/mixing/PropertyValidator.java
  src/main/java/sirius/db/mixing/annotations/ValidatedBy.java
  src/test/java/sirius/db/mongo/ValidatedByTestEntity.java
  src/test/java/sirius/db/mongo/validators/StringTestPropertyValidator.java
  src/test/kotlin/sirius/db/mixing/annotations/ValidatedByTest.kt
  src/test/resources/test_de.properties
Labels: 🧬 Enhancement
