Repository scireum/sirius-db, pull requests merged in 2023-08, with the labels that each got.

#588 Passes validated property to the validator
  src/main/java/sirius/db/mixing/Property.java
  src/main/java/sirius/db/mixing/PropertyValidator.java
  src/test/java/sirius/db/mongo/validators/StringTestPropertyValidator.java
Labels: 🧬 Enhancement, 👶🏻 Trivial, 💣 BREAKING CHANGE

#589 Improves log entries for cascading deletion
  src/main/resources/db_de.properties
Labels: 🧬 Enhancement, 👶🏻 Trivial

#586 Project update and code cleanup
  pom.xml
  src/main/java/sirius/db/es/Bucket.java
  src/main/java/sirius/db/es/Elastic.java
  src/main/java/sirius/db/es/ElasticEntity.java
  src/main/java/sirius/db/jdbc/constraints/SQLFilterFactory.java
  src/main/java/sirius/db/mixing/query/constraints/FilterFactory.java
  src/main/java/sirius/db/text/PatternExtractProcessor.java
  src/main/java/sirius/db/text/ReduceCharacterProcessor.java
  src/test/java/sirius/db/text/ReduceCharactersProcessorTest.java
Labels: 💣 BREAKING CHANGE, 🛠️ Maintenance
