Repository scireum/sirius-db, pull requests merged in 2023-06, with the labels that each got.

#572 ElasticSearch: More robust and useful query across multiple indices
  src/main/java/sirius/db/es/Elastic.java
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#573 ElasticSearch: Adds variant of selectMultiple that takes a list of types
  src/main/java/sirius/db/es/Elastic.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#574 Permits EntityRefs to fetch values using a secondary node
  src/main/java/sirius/db/es/types/ElasticRef.java
  src/main/java/sirius/db/jdbc/SQLEntityRef.java
  src/main/java/sirius/db/mixing/types/BaseEntityRef.java
  src/main/java/sirius/db/mongo/types/MongoRef.java
Labels: 🧬 Enhancement

#577 ES: Uses more consistent naming for custom sorting functions
  src/main/java/sirius/db/es/AggregationBuilder.java
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/es/SortBuilder.java
  src/test/java/sirius/db/es/ElasticQuerySpec.groovy
Labels:  💣 BREAKING CHANGE

#578 ES: Correctly checks entity index name when trying to convert entity
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 👶🏻 Trivial, 🐛 Bugfix
