Repository scireum/sirius-db, pull requests merged in 2023-09, with the labels that each got.

#591 Introduces a non-strict validation mode
  src/main/java/sirius/db/mixing/Property.java
  src/main/java/sirius/db/mixing/annotations/ValidatedBy.java
  src/test/java/sirius/db/mongo/ValidatedByTestEntity.java
  src/test/kotlin/sirius/db/mixing/annotations/ValidatedByTest.kt
Labels: 🧬 Enhancement

#593 Adds support for "dis_max" queries for Elasticsearch
  src/main/java/sirius/db/es/constraints/ElasticFilterFactory.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#594 Returns the proper constraint.
  src/main/java/sirius/db/es/constraints/ElasticFilterFactory.java
Labels: 👶🏻 Trivial, 🐛 Bugfix

#595 Updates sirius to latest versions
  pom.xml
Labels: ⬆️ Dependencies, 🛠️ Maintenance
