Repository scireum/sirius-db, pull requests merged in 2023-12, with the labels that each got.

#602 Simplifies code by utilizing sequenced collection helpers
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/es/LowLevelClient.java
  src/main/java/sirius/db/es/constraints/BoolQueryBuilder.java
  src/main/java/sirius/db/es/constraints/ElasticFilterFactory.java
  src/main/java/sirius/db/es/suggest/SuggestionResult.java
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/main/java/sirius/db/jdbc/constraints/CompoundValue.java
  src/main/java/sirius/db/mixing/properties/MultiPointLocationProperty.java
  src/main/java/sirius/db/mixing/query/BaseQuery.java
  src/main/java/sirius/db/mixing/query/constraints/FilterFactory.java
  src/main/java/sirius/db/mongo/MongoQuery.java
  src/main/java/sirius/db/text/PipelineProcessor.java
Labels: 🎁 Next version, 🛠️ Maintenance

#601 Use streamBlockwise for cascadeDelete
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/jdbc/SmartQuery.java
  src/main/java/sirius/db/mixing/properties/BaseEntityRefListProperty.java
  src/main/java/sirius/db/mixing/properties/BaseEntityRefProperty.java
  src/main/java/sirius/db/mixing/query/Query.java
  src/main/java/sirius/db/mongo/MongoQuery.java
  src/main/resources/component-060-db.conf
  src/test/resources/test.conf
Labels: 🐛 Bugfix, 💣 BREAKING CHANGE

#603 update some dependencies.
  pom.xml
  src/main/java/sirius/db/jdbc/Database.java
  src/test/kotlin/sirius/db/testutil/MongoMocks.kt
Labels: ⬆️ Dependencies
