Repository scireum/sirius-db, pull requests merged in 2024-05, with the labels that each got.

#650 Smart Query - Adds the possibility to use index hints
  src/main/java/sirius/db/jdbc/SmartQuery.java
Labels: 🧬 Enhancement

#656 Upgrades Jedis library
  pom.xml
  src/main/java/sirius/db/redis/RedisDB.java
Labels: ⬆️ Dependencies

#655 Tokenization - Prevent detecting plus and ampersand as hard word boundary
  src/main/java/sirius/db/text/BasicIndexTokenizer.java
  src/main/java/sirius/db/text/BypassProcessor.java
  src/main/java/sirius/db/text/DeduplicateProcessor.java
  src/main/java/sirius/db/text/PatternExtractProcessor.java
  src/main/java/sirius/db/text/PatternReplaceProcessor.java
  src/main/java/sirius/db/text/PatternSplitProcessor.java
  src/main/java/sirius/db/text/PipelineProcessor.java
  src/test/java/sirius/db/text/BasicIndexTokenizerTest.java
  src/test/java/sirius/db/text/PatternExtractProcessorTest.java
  src/test/java/sirius/db/text/PatternReplaceProcessorTest.java
  src/test/java/sirius/db/text/PatternSplitProcessorTest.java
  src/test/java/sirius/db/text/PipelineProcessorTest.java
  src/test/java/sirius/db/text/ReduceCharactersProcessorTest.java
  src/test/java/sirius/db/text/ToLowercaseProcessorTest.java
  src/test/java/sirius/db/text/TokenLimitProcessorTest.java
  src/test/java/sirius/db/text/TokenProcessorTest.java
  src/test/kotlin/sirius/db/text/BasicIndexTokenizerTest.kt
  src/test/kotlin/sirius/db/text/PatternExtractProcessorTest.kt
  src/test/kotlin/sirius/db/text/PatternReplaceProcessorTest.kt
  src/test/kotlin/sirius/db/text/PatternSplitProcessorTest.kt
  src/test/kotlin/sirius/db/text/PipelineProcessorTest.kt
  src/test/kotlin/sirius/db/text/ReduceCharactersProcessorTest.kt
  src/test/kotlin/sirius/db/text/ToLowercaseProcessorTest.kt
  src/test/kotlin/sirius/db/text/TokenLimitProcessorTest.kt
  src/test/kotlin/sirius/db/text/TokenProcessorTest.kt
Labels: 🧬 Enhancement, 🛠️ Maintenance
