Repository scireum/sirius-db, pull requests merged in 2024-04, with the labels that each got.

#648 Optimizes some system generates queries based on casing annotations
  src/main/java/sirius/db/jdbc/constraints/SQLQueryCompiler.java
  src/main/java/sirius/db/mixing/annotations/LowerCase.java
  src/main/java/sirius/db/mixing/annotations/UpperCase.java
  src/main/java/sirius/db/mixing/query/QueryCompiler.java
  src/main/java/sirius/db/mixing/query/QueryField.java
  src/main/java/sirius/db/mongo/constraints/MongoQueryCompiler.java
Labels: 🧬 Enhancement

#652 Update sirius parent to version targeting Java 22
  .drone.yml
  pom.xml
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#653 Update sirius parent to version with Jackson downgrade
  pom.xml
  src/main/java/sirius/db/es/ElasticQuery.java
Labels: 🐛 Bugfix, ⬆️ Dependencies, 🛠️ Maintenance
