Repository scireum/sirius-db, pull requests merged in 2024-12, with the labels that each got.

#666 Switch project to Java 23
  .drone.yml
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#667 Defines an important constant for a fallback value
  src/main/java/sirius/db/es/ElasticQuery.java
  src/main/java/sirius/db/mixing/annotations/Length.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#668 Improves the BaseEntityCache and BaseEntityRef
  src/main/java/sirius/db/mixing/properties/BaseEntityRefProperty.java
  src/main/java/sirius/db/mixing/types/BaseEntityRef.java
  src/main/java/sirius/db/util/BaseEntityCache.java
  src/test/kotlin/sirius/db/jdbc/SmartQueryKotlinTest.kt
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#669 Fixes amount propery persistance scale handling
  src/main/java/sirius/db/mixing/properties/AmountProperty.java
  src/test/java/sirius/db/jdbc/DataTypesEntity.java
  src/test/java/sirius/db/mongo/properties/MongoAmountEntity.java
  src/test/kotlin/sirius/db/jdbc/DataTypesTest.kt
  src/test/kotlin/sirius/db/mongo/properties/MongoAmountPropertyTest.kt
Labels: 🐛 Bugfix
