Repository scireum/sirius-db, pull requests merged in 2025-04, with the labels that each got.

#679 Redis - Allow to control whether client info is sent for each pool
  src/main/java/sirius/db/redis/RedisDB.java
  src/main/resources/component-060-db.conf
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#681 Redis - Invert default for client info flag
  src/main/java/sirius/db/redis/RedisDB.java
  src/main/resources/component-060-db.conf
Labels: 👶🏻 Trivial, 🐛 Bugfix

#682 Lokalise: Translations update
  src/main/resources/db_de.properties
Labels: 🛠️ Maintenance

#683 Upgrades mongo db container to 8.0.8
  src/test/resources/docker-db.yml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#684 Lokalise: Translations update
  pom.xml
  src/main/resources/db_cs.properties
  src/main/resources/db_de.properties
  src/main/resources/db_en.properties
  src/main/resources/db_es.properties
  src/main/resources/db_fr.properties
  src/main/resources/db_it.properties
  src/main/resources/db_nl.properties
  src/main/resources/db_pl.properties
  src/main/resources/db_sk.properties
Labels: ⬆️ Dependencies, 🛠️ Maintenance

#686 Remove unused Qdrant vector DB wrapper
  src/main/java/sirius/db/qdrant/Match.java
  src/main/java/sirius/db/qdrant/Point.java
  src/main/java/sirius/db/qdrant/Qdrant.java
  src/main/java/sirius/db/qdrant/QdrantDatabase.java
  src/main/java/sirius/db/qdrant/README.md
  src/main/java/sirius/db/qdrant/Search.java
  src/main/resources/component-060-db.conf
  src/test/kotlin/sirius/db/qdrant/QdrantTest.kt
  src/test/resources/docker-db.yml
  src/test/resources/test.conf
Labels: 👶🏻 Trivial, 💣 BREAKING CHANGE, 🛠️ Maintenance
