Repository scireum/sirius-db, pull requests merged in 2025-02, with the labels that each got.

#671 Upgrades the mongodb container to 7.0.16
  src/test/resources/docker-db.yml
Labels: 👶🏻 Trivial, ⬆️ Dependencies

#675 Update libraries to latest versions and link to change logs
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#674 Fixes amount with large scale persistence
  src/main/java/sirius/db/mixing/properties/AmountProperty.java
  src/test/java/sirius/db/es/properties/ESDataTypesEntity.java
  src/test/java/sirius/db/jdbc/DataTypesEntity.java
  src/test/java/sirius/db/mongo/properties/MongoAmountEntity.java
  src/test/kotlin/sirius/db/es/properties/ElasticDataTypesTest.kt
  src/test/kotlin/sirius/db/jdbc/DataTypesTest.kt
  src/test/kotlin/sirius/db/mongo/properties/MongoAmountPropertyTest.kt
Labels: 🐛 Bugfix
